version: '3.8'
services:
  web:
    build: .
    ports:
      - "6000:6000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
